---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: "DELETE, GET, OPTIONS, PATCH, POST, PUT"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "1" #Deliberatly limited so can demo HTTP 503 response
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - products.company.com
    secretName: company-cert
  rules:
  - host: products.company.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: products-api-service
            port:
              number: 80
