---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-mq
spec:
  serviceName: rabbit-mq-service
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rabbit-mq # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbit-mq
        env: 
        - name: RABBITMQ_NODENAME
          value: rabbit@localhost      
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
          name: http
        - containerPort: 5672
          name: amqp      
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 15672
    name: http
    protocol: TCP
    targetPort: 15672
  - port: 5672
    name: amqp
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbit-mq
  type: LoadBalancer

