global:
  env: local
  database_connection_string: bW9uZ29kYjovL2FkbWluOm1vbmdvZGItazhzLWRlbW9AZGF0YWJhc2Utc2VydmljZToyNzAxNw==
  domain: local.com
  loadBalancerIP: 20.47.116.6 # Must be standard if AKS LoadBalancer is standard, basic if AKS LoadBalancer is basic
contacts-api:
  image:
    tag: latest
database:
  image:
    tag: latest
queue:
  nodename: rabbit@localhost
registry:
  image:
    tag: latest
test-data-management:
  image:
    tag: latest
web:
  image:
    tag: latest