global:
  env: local
  database_connection_string: bW9uZ29kYjovL2RhdGFiYXNlLXNlcnZpY2U6MjcwMTc= # or bW9uZ29kYjovL2FkbWluOm1vbmdvZGItazhzLWRlbW9AZGF0YWJhc2Utc2VydmljZToyNzAxNw==
  api_hostname: api.local.com
  app_hostname: app.local.com
contacts-api:
  image:
    tag: latest
database:
  image:
    tag: latest
queue:
  nodename: rabbit@localhost
registry:
  image:
    tag: latest
test-data-management:
  image:
    tag: latest
web:
  image:
    tag: latest