apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Chart.Name}}
spec:
  template:
    spec:
      containers:
        - name: {{.Chart.Name}}
          env: 
          - name: mongoDbConnectionString
            valueFrom:
              secretKeyRef:
                name: {{.Chart.Name}}-secrets
                key: mongoDbConnectionString
                optional: false
          image: paulgilchrist/mongodb-insert:{{.Values.image.tag}}
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
