apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  ports:
    - port: 27017
      name: database
  selector:
    app: database
  type: LoadBalancer # so a listner can be outside the cluster without needing an ingress