# kubectl describe apiservice v1beta1.metrics.k8s.io
# kubectl top pod -A
# kubectl top node
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: contacts-api-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contacts-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 1Gi
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # default = 300 and should be set to 300 or more for production
      policies:
      - type: Pods # default = Percent
        value: 1 # default = 100
        periodSeconds: 300 # default = 300 and should be set to 300 or more for production
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods # default = Percent
        value: 1 # default = 100 allowing the number of pods to double each time
        periodSeconds: 60


