apiVersion: v1
kind: Service
metadata:
  name: products-api-v1-service
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: products-api-v1
  type: ClusterIP
