apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api
  namespace: demo
spec:
  #replicas: 1 # remove this if using horizontal auto-scaling
  selector:
    matchLabels:
      app: contacts-api # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: contacts-api # has to match .spec.selector.matchLabels
      annotations:
        # dapr.io/enabled: "true"
        # dapr.io/app-id: "contacts-api"
        # dapr.io/app-port: "80"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: contacts-api
        env: 
        - name: BasePath
          value: /contacts
        - name: ContactsCollectionName
          value: contacts
        - name: DatabaseConnectionString
          valueFrom:
            secretKeyRef:
              name: contacts-api-secrets
              key: DatabaseConnectionString
              optional: false
        - name: DatabaseName
          value: mongotest
        - name: QueueConnectionString # same as HostName for QueueType="RabbitMQ"
          value: queue-service
        - name: QueueName
          value: contacts
        - name: QueueType # valid options are "AzureServiceBus", "Dapr", or "RabbitMQ"
          value: RabbitMQ
        - name: TelemetryConnectionString # blank if TelemetryType="Console"
          value: 
        - name: TelemetryType # valid options are "AppInsights", "Console", or "Zipkin"
          value: Console
        image: paulgilchrist/mongodb-api:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        ports:
        - containerPort: 80
          name: contacts-api
        resources:
          limits:
            cpu: 125m
            memory: 1.5Gi
          requests:
            cpu: 50m
            memory: 0.5Gi