---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  # namespace: default
spec:
  storageClassName: aks-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
