apiVersion: batch/v1
kind: Job
metadata:
  name: test-data-management
  namespace: demo
spec:
  template:
    spec:
      containers:
        - name: test-data-management
          env: 
          - name: mongoDbConnectionString
            valueFrom:
              secretKeyRef:
                name: test-data-management-secrets
                key: mongoDbConnectionString
                optional: false
          image: paulgilchrist/mongodb-insert:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
