apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-pubsub-rabbitmq
  namespace: demo
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://queue:5672" # Kubernetes service name
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
scopes:
  - contacts-api
