# kubectl describe apiservice v1beta1.metrics.k8s.io
# kubectl top pod -A
# kubectl top node
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: products-api-v2-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-api-v2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: 1Gi


