apiVersion: v1
kind: Service
metadata:
  name: queue-service
{{- if ne .Values.global.env "local" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: mc_aks_testing_westus 
{{- end }}
spec:
{{- if ne .Values.global.env "local" }}
  externalTrafficPolicy: Cluster
  loadBalancerIP:  {{ .Values.loadBalancerIP }}
{{- end }}
  ports:
    - port: 15672
      name: http
    - port: 5672
      name: amqp
  selector:
    app: queue
  type: LoadBalancer # so a listner can be outside the cluster without needing an ingress
