apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
{{- if eq .Values.global.env "local" }}
  volumeName: database-pv
{{- else }}
  storageClassName: managed-premium
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

