apiVersion: v1
kind: Service
metadata:
  name: database-service
{{- if ne .Values.global.env "local" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: mc_aks_testing_westus 
{{- end }}
spec:
{{- if ne .Values.global.env "local" }}
  externalTrafficPolicy: Cluster
  loadBalancerIP: 20.47.116.6 # Must be standard if AKS LoadBalancer is standard, basic if AKS LoadBalancer is basic
{{- end }}
  ports:
    - port: 27017
      name: database
  selector:
    app: database
  type: LoadBalancer # so a listner can be outside the cluster without needing an ingress
