apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: local-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: database-pv
  resources:
    requests:
      storage: 1Gi
