{{- if eq .Values.env "local" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Chart.Name}}-sc
allowVolumeExpansion: true
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
