apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
{{- if ne .Values.global.env "local" }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: mc_aks_testing_westus 
{{- end }}
spec:
  ports:
    - port: 27017
      name: {{.Chart.Name}}
  selector:
    app: {{.Chart.Name}}
  type: ClusterIP
