apiVersion: apps/v1
kind: StatefulSet # StatefulSet allows pointing each to its own storage location
metadata:
  name: {{.Chart.Name}}
spec:
  serviceName: {{.Chart.Name}}-service
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{.Chart.Name}} # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: {{.Chart.Name}} # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{.Chart.Name}}
        command: ["mongod"]
        args: ["--dbpath=/data/db", "--bind_ip_all"] #, "--auth"
        image: mongo:{{.Values.image.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: database
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db # must match configmap dbPath and "command" args
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{.Chart.Name}}-pvc
